import type { Media } from './types';

/**
 * Catálogo de doramas.
 *
 * Os pôsteres ainda não vieram do protótipo, então estes títulos ficam sem `img`
 * e caem no bloco em degradê da marca: o mesmo fallback usado em todo o app.
 * Basta preencher `img` com um arquivo em `public/posters/` para ativá-los.
 */
export const DORAMAS: readonly Media[] = [
  {
    id: 61,
    type: 'dorama',
    title: 'Pousando no Amor',
    genre: 'Romance',
    year: 2019,
    epMin: 70,
    rating: 8.7,
    img: '',
    seasons: 1,
    epCount: 16,
    country: 'Coreia do Sul',
    network: 'tvN',
    cast: 'Hyun Bin, Son Ye-jin, Seo Ji-hye',
    synopsis:
      'Uma herdeira sul-coreana cai de parapente do lado errado da fronteira e é escondida por um oficial norte-coreano que jura protegê-la.',
  },
  {
    id: 62,
    type: 'dorama',
    title: 'Goblin: O Guardião Solitário',
    genre: 'Fantasia',
    year: 2016,
    epMin: 75,
    rating: 8.6,
    img: '',
    seasons: 1,
    epCount: 16,
    country: 'Coreia do Sul',
    network: 'tvN',
    cast: 'Gong Yoo, Kim Go-eun, Lee Dong-wook',
    synopsis:
      'Um general amaldiçoado com a imortalidade divide a casa com um ceifador amnésico e procura a noiva capaz de encerrar sua vida eterna.',
  },
  {
    id: 63,
    type: 'dorama',
    title: 'Descendentes do Sol',
    genre: 'Romance',
    year: 2016,
    epMin: 60,
    rating: 8.2,
    img: '',
    seasons: 1,
    epCount: 16,
    country: 'Coreia do Sul',
    network: 'KBS2',
    cast: 'Song Joong-ki, Song Hye-kyo, Jin Goo',
    synopsis:
      'Um capitão das forças especiais e uma cirurgiã se apaixonam em uma zona de guerra, onde cada plantão pode ser o último.',
  },
  {
    id: 64,
    type: 'dorama',
    title: 'Hospital Playlist',
    genre: 'Drama',
    year: 2020,
    epMin: 90,
    rating: 8.9,
    img: '',
    seasons: 2,
    epCount: 12,
    country: 'Coreia do Sul',
    network: 'tvN',
    cast: 'Jo Jung-suk, Yoo Yeon-seok, Jung Kyung-ho',
    synopsis:
      'Cinco médicos amigos desde a faculdade dividem plantões, perdas e ensaios de banda em um hospital que nunca dorme.',
  },
  {
    id: 65,
    type: 'dorama',
    title: 'Itaewon Class',
    genre: 'Drama',
    year: 2020,
    epMin: 70,
    rating: 8.2,
    img: '',
    seasons: 1,
    epCount: 16,
    country: 'Coreia do Sul',
    network: 'JTBC',
    cast: 'Park Seo-joon, Kim Da-mi, Yoo Jae-myung',
    synopsis:
      'Depois de perder tudo para um conglomerado, um ex-detento abre um bar em Itaewon e monta uma equipe improvável para derrubar o império rival.',
  },
  {
    id: 66,
    type: 'dorama',
    title: 'Vincenzo',
    genre: 'Crime',
    year: 2021,
    epMin: 80,
    rating: 8.4,
    img: '',
    seasons: 1,
    epCount: 20,
    country: 'Coreia do Sul',
    network: 'tvN',
    cast: 'Song Joong-ki, Jeon Yeo-been, Ok Taec-yeon',
    synopsis:
      'Um advogado da máfia italiana volta à Coreia para recuperar ouro escondido sob um prédio e acaba defendendo seus moradores com métodos nada legais.',
  },
  {
    id: 67,
    type: 'dorama',
    title: 'Hotel Del Luna',
    genre: 'Fantasia',
    year: 2019,
    epMin: 75,
    rating: 8.1,
    img: '',
    seasons: 1,
    epCount: 16,
    country: 'Coreia do Sul',
    network: 'tvN',
    cast: 'IU, Yeo Jin-goo, Shin Jung-geun',
    synopsis:
      'Um hotel invisível hospeda almas em trânsito, e sua dona milenar precisa de um gerente humano para enfim se libertar do próprio passado.',
  },
  {
    id: 68,
    type: 'dorama',
    title: 'Meu Amor das Estrelas',
    genre: 'Romance',
    year: 2013,
    epMin: 65,
    rating: 8.3,
    img: '',
    seasons: 1,
    epCount: 21,
    country: 'Coreia do Sul',
    network: 'SBS',
    cast: 'Kim Soo-hyun, Jun Ji-hyun, Park Hae-jin',
    synopsis:
      'Um alienígena preso na Terra há quatro séculos conta os dias para voltar ao seu planeta: até se apaixonar pela atriz mais famosa do país.',
  },
  {
    id: 69,
    type: 'dorama',
    title: 'Reply 1988',
    genre: 'Comédia',
    year: 2015,
    epMin: 90,
    rating: 9.1,
    img: '',
    seasons: 1,
    epCount: 20,
    country: 'Coreia do Sul',
    network: 'tvN',
    cast: 'Lee Hye-ri, Ryu Jun-yeol, Go Kyung-pyo',
    synopsis:
      'Cinco famílias de um mesmo beco em Seul atravessam os anos 80 entre apagões, primeiros amores e portas que nunca se trancam.',
  },
  {
    id: 70,
    type: 'dorama',
    title: 'Alice in Borderland',
    genre: 'Suspense',
    year: 2020,
    epMin: 50,
    rating: 7.7,
    img: '',
    seasons: 2,
    epCount: 8,
    country: 'Japão',
    network: 'Netflix',
    cast: 'Kento Yamazaki, Tao Tsuchiya, Nijiro Murakami',
    synopsis:
      'Um gamer sem rumo acorda numa Tóquio deserta onde sobreviver exige vencer jogos letais e gastar o tempo de vida que sobra.',
  },
  {
    id: 71,
    type: 'dorama',
    title: 'Midnight Diner',
    genre: 'Drama',
    year: 2009,
    epMin: 25,
    rating: 8.6,
    img: '',
    seasons: 3,
    epCount: 10,
    country: 'Japão',
    network: 'TBS',
    cast: 'Kaoru Kobayashi, Joe Odagiri, Yutaka Matsushige',
    synopsis:
      'Um pequeno restaurante em Shinjuku abre da meia-noite às sete e serve, junto com cada prato, a história de quem senta ao balcão.',
  },
  {
    id: 72,
    type: 'dorama',
    title: 'Meteor Garden',
    genre: 'Romance',
    year: 2018,
    epMin: 45,
    rating: 7.4,
    img: '',
    seasons: 1,
    epCount: 18,
    country: 'China',
    network: 'Hunan TV',
    cast: 'Shen Yue, Dylan Wang, Darren Chen',
    synopsis:
      'Bolsista numa universidade de elite, uma jovem enfrenta o quarteto mais rico do campus e desmonta a arrogância do líder do grupo.',
  },
  {
    id: 73,
    type: 'dorama',
    title: 'A Ilha do Silêncio',
    genre: 'Suspense',
    year: 2024,
    epMin: 55,
    rating: 8.0,
    img: '',
    seasons: 1,
    epCount: 12,
    country: 'Tailândia',
    network: 'GMM 25',
    cast: 'Mai Davika, Nadech Kugimiya, Urassaya Sperbund',
    synopsis:
      'Uma repórter investiga o desaparecimento de turistas numa ilha paradisíaca onde todos os moradores contam exatamente a mesma versão.',
  },
  {
    id: 74,
    type: 'dorama',
    title: 'Primavera em Busan',
    genre: 'Romance',
    year: 2025,
    epMin: 60,
    rating: 8.5,
    img: '',
    seasons: 1,
    epCount: 14,
    country: 'Coreia do Sul',
    network: 'Lumio Original',
    cast: 'Bae Suzy, Nam Joo-hyuk, Kim Hye-ja',
    synopsis:
      'Uma chef que voltou à cidade natal para fechar o restaurante da avó reencontra o primeiro amor e descobre uma receita que a família escondia.',
  },
];

export const DORAMA_GENRES: readonly string[] = [
  'Todos',
  'Romance',
  'Drama',
  'Fantasia',
  'Crime',
  'Suspense',
  'Comédia',
];

/** Sigla do país exibida no card de cada dorama, no lugar de bandeirinha emoji. */
export const COUNTRY_CODE: Readonly<Record<string, string>> = {
  'Coreia do Sul': 'KR',
  'Japão': 'JP',
  China: 'CN',
  'Tailândia': 'TH',
  Turquia: 'TR',
};
