import type { Media } from './types';

/**
 * Catálogo de novelas turcas.
 *
 * Mesma situação dos doramas: sem pôster por enquanto, então caem no bloco em
 * degradê. Preencher `img` com um arquivo em `public/posters/` já os ativa.
 */
export const TURCAS: readonly Media[] = [
  {
    id: 81,
    type: 'turca',
    title: 'Amor Eterno',
    genre: 'Romance',
    year: 2015,
    epMin: 120,
    rating: 8.6,
    img: '',
    seasons: 2,
    epCount: 14,
    country: 'Turquia',
    network: 'Star TV',
    cast: 'Burak Özçivit, Neslihan Atagül, Kaan Urgancıoğlu',
    synopsis:
      'Um fotógrafo apaixonado e uma jovem de origem humilde se encontram num mundo de riqueza e vingança que ameaça separá-los para sempre.',
  },
  {
    id: 82,
    type: 'turca',
    title: 'Mãe',
    genre: 'Drama',
    year: 2016,
    epMin: 110,
    rating: 8.9,
    img: '',
    seasons: 1,
    epCount: 13,
    country: 'Turquia',
    network: 'Star TV',
    cast: 'Cansu Dere, Beren Gökyıldız, Vahide Perçin',
    synopsis:
      'Uma professora descobre que sua aluna sofre maus-tratos em casa e toma a decisão de assumi-la como filha, custe o que custar.',
  },
  {
    id: 83,
    type: 'turca',
    title: 'Fatmagül',
    genre: 'Drama',
    year: 2010,
    epMin: 120,
    rating: 8.4,
    img: '',
    seasons: 2,
    epCount: 16,
    country: 'Turquia',
    network: 'Kanal D',
    cast: 'Beren Saat, Engin Akyürek, Firat Çelik',
    synopsis:
      'Depois de um crime que destrói sua vida numa vila do litoral, uma jovem enfrenta o silêncio de toda uma cidade em busca de justiça.',
  },
  {
    id: 84,
    type: 'turca',
    title: 'Mulher',
    genre: 'Drama',
    year: 2017,
    epMin: 115,
    rating: 8.5,
    img: '',
    seasons: 2,
    epCount: 14,
    country: 'Turquia',
    network: 'Fox Türkiye',
    cast: 'Özge Özpirinççi, Caner Cindoruk, Bennu Yıldırımlar',
    synopsis:
      'Viúva e com dois filhos pequenos, Bahar luta por cada dia em Istambul enquanto o passado da própria mãe volta para cobrar respostas.',
  },
  {
    id: 85,
    type: 'turca',
    title: 'O Século Magnífico',
    genre: 'Época',
    year: 2011,
    epMin: 130,
    rating: 8.7,
    img: '',
    seasons: 4,
    epCount: 12,
    country: 'Turquia',
    network: 'Show TV',
    cast: 'Halit Ergenç, Meryem Uzerli, Nebahat Çehre',
    synopsis:
      'No auge do Império Otomano, o sultão Solimão governa três continentes enquanto uma escrava se torna a mulher mais poderosa do harém.',
  },
  {
    id: 86,
    type: 'turca',
    title: 'Amor Proibido',
    genre: 'Romance',
    year: 2008,
    epMin: 90,
    rating: 8.2,
    img: '',
    seasons: 2,
    epCount: 15,
    country: 'Turquia',
    network: 'Kanal D',
    cast: 'Beren Saat, Kıvanç Tatlıtuğ, Selçuk Yöntem',
    synopsis:
      'Casada com um homem muito mais velho e muito rico, Bihter se entrega a uma paixão proibida dentro da própria casa.',
  },
  {
    id: 87,
    type: 'turca',
    title: 'Bata à Minha Porta',
    genre: 'Comédia',
    year: 2020,
    epMin: 120,
    rating: 8.1,
    img: '',
    seasons: 2,
    epCount: 13,
    country: 'Turquia',
    network: 'Fox Türkiye',
    cast: 'Hande Erçel, Kerem Bürsin, Neslihan Yeldan',
    synopsis:
      'Uma estudante de arquitetura finge um noivado com o herdeiro que odeia para garantir a bolsa dos seus sonhos.',
  },
  {
    id: 88,
    type: 'turca',
    title: 'Pássaro Madrugador',
    genre: 'Comédia',
    year: 2018,
    epMin: 120,
    rating: 8.0,
    img: '',
    seasons: 1,
    epCount: 16,
    country: 'Turquia',
    network: 'Star TV',
    cast: 'Can Yaman, Demet Özdemir, Öznur Serçeler',
    synopsis:
      'Uma ilustradora desastrada vai parar na agência de publicidade do herdeiro mais mal-humorado de Istambul: como assistente dele.',
  },
  {
    id: 89,
    type: 'turca',
    title: 'A Cova',
    genre: 'Ação',
    year: 2017,
    epMin: 140,
    rating: 8.6,
    img: '',
    seasons: 4,
    epCount: 12,
    country: 'Turquia',
    network: 'Show TV',
    cast: 'Aras Bulut İynemli, Erkan Kolçak Köstendil, Rıza Kocaoğlu',
    synopsis:
      'O filho caçula de uma família que controla um bairro de Istambul volta para casa e é arrastado de volta ao crime que jurou deixar.',
  },
  {
    id: 90,
    type: 'turca',
    title: 'Infiltrado',
    genre: 'Suspense',
    year: 2016,
    epMin: 135,
    rating: 8.5,
    img: '',
    seasons: 1,
    epCount: 13,
    country: 'Turquia',
    network: 'Show TV',
    cast: 'Çağatay Ulusoy, Aras Bulut İynemli, Mustafa Üstündağ',
    synopsis:
      'Dois irmãos separados na infância crescem em lados opostos da lei e se reencontram numa operação em que nenhum dos dois pode revelar quem é.',
  },
  {
    id: 91,
    type: 'turca',
    title: 'Hercai',
    genre: 'Romance',
    year: 2019,
    epMin: 125,
    rating: 7.9,
    img: '',
    seasons: 3,
    epCount: 12,
    country: 'Turquia',
    network: 'ATV',
    cast: 'Akın Akınözü, Ebru Şahin, Ayda Aksel',
    synopsis:
      'Uma jovem se casa por vingança com o herdeiro da família que destruiu a sua: e descobre que o ódio e o amor moram muito perto.',
  },
  {
    id: 92,
    type: 'turca',
    title: 'Norte e Sul',
    genre: 'Drama',
    year: 2011,
    epMin: 110,
    rating: 8.3,
    img: '',
    seasons: 2,
    epCount: 14,
    country: 'Turquia',
    network: 'Kanal D',
    cast: 'Kıvanç Tatlıtuğ, Buğra Gülsoy, Öykü Karayel',
    synopsis:
      'Dois irmãos criados na mesma casa seguem destinos opostos depois que um acidente e uma mentira decidem qual dos dois paga a conta.',
  },
  {
    id: 93,
    type: 'turca',
    title: 'Maré Alta',
    genre: 'Romance',
    year: 2013,
    epMin: 120,
    rating: 8.2,
    img: '',
    seasons: 2,
    epCount: 13,
    country: 'Turquia',
    network: 'Star TV',
    cast: 'Çağatay Ulusoy, Serenay Sarıkaya, Barış Falay',
    synopsis:
      'Um garoto de periferia ganha a chance de estudar num colégio de elite à beira-mar e descobre que pertencer custa mais do que imaginava.',
  },
  {
    id: 94,
    type: 'turca',
    title: 'A Herdeira de Istambul',
    genre: 'Época',
    year: 2025,
    epMin: 115,
    rating: 8.4,
    img: '',
    seasons: 1,
    epCount: 12,
    country: 'Turquia',
    network: 'Lumio Original',
    cast: 'Fahriye Evcen, Burak Deniz, Şükrü Özyıldız',
    synopsis:
      'Nos anos 1920, a filha de um comerciante assume os negócios da família e enfrenta uma cidade que não aceita uma mulher no comando.',
  },
];

export const TURCA_GENRES: readonly string[] = [
  'Todos',
  'Romance',
  'Drama',
  'Comédia',
  'Ação',
  'Suspense',
  'Época',
];
